# Generated by Django 3.1.4 on 2020-12-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    max_length=250, verbose_name='Название книги')),
                ('author', models.CharField(
                    max_length=200, verbose_name='Автор книги')),
                ('rating', models.IntegerField(verbose_name='Рейтинг книги')),
                ('date', models.DateTimeField(auto_now_add=True,
                                              verbose_name='Дата размещения на сервисе')),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Пользователь, разместивший книгу')),
            ],
        ),
    ]
